### ISSUE TITLE
Problems with loaded model

### ISSUE THREAD

**Issue by guilhermevrs** [tariqdaouda/Mariana#18]
Hello again @tariqdaouda,

Looks like I am facing a challenge here hehe.

What I am trying to do is actually use the already trained model in my system.

So I trained my model with the parameters I experimented to get me the best results and your trainer saved the parameters into the pkl file.

To load the model I used the code in the documentation:
`import cPickle

`mlp = cPickle.load(open("myMLP.mariana.pkl"))`

But mlp is a dict object, don't have the propagate function.

So I looked it up in the code and found the LoadModel method. I tried to load the model with the following code:

`mlp_state = MN.loadModel("mlp_state/state-config")`

Worked! Now I have the method propagate. To get the output layer result, I used this code (from test.py in the repository):

`o = mlp_state.outputs.values()[0]
mlp_state.classify(o, inp = numpy.asarray(inputSet))
`
But first I was getting an error that the dimensions of the input are wrong:
`TypeError: ('Bad input argument to theano function with name "/media/guilhermevrs/Data/Documentos/Academico/TCC-code/Mariana/Mariana/wrappers.py:58"  at index 1(0-based)', 'Wrong number of dimensions: expected 2, got 1 with shape (42,).')`

My input is of 42 nodes. I even trained the model with 42.

So I placed my input data as the first element of an array. Now the error I am getting this one:

`TypeError: Tried to provide value for implicit input: <TensorType(float64, matrix)>`

Can you give me a light here, please?

**Comment by tariqdaouda** [comment]
Hi @guilhermevrs!

Thanks for letting me know that the doc is out of date on model loading. Both tests and loading models trained with the trainer work for me. Could you try to do a git pull to make sure that you have the last version? If you already have the last version:

- Do you use the Theano version from my repository?
- Do the tests work?

If the answer is yes to both questions, have you done anything particular or different form the examples for the creation of your model or the training?

**Comment by guilhermevrs** [comment]
Hi @tariqdaouda,

Thanks for your answer!
Things are a bit crazy this week, I will get back to you and this matter asap

Cheers

**Comment by tariqdaouda** [comment]
No problem.
