### ISSUE TITLE
missing import Mariana.settings as MSET

### ISSUE THREAD

**Issue by andrewcz** [tariqdaouda/Mariana#21]
Hi,
I hope your well.
I was looking for the above file.
It comes with an error when i run the examples.
Many thanks,
Best,
Andrew

**Comment by tariqdaouda** [comment]
Hi Andrew!
I fine thanks, I hope you are well too, could you tell me which file is missing the import?

Best,
T.

**Comment by tariqdaouda** [comment]
Fixed!
